services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh run.sh
    container_name: api_java
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    ports:
      - "8080:8080"
      - "35729:35729"
      - "5005:5005"

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: api_java
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: