services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_java
    ports:
      - "8080:8080"

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: api_java
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: